/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	volumepathv1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/volumepath/v1alpha1"
	versioned "github.com/upmio/dbscale-kube/pkg/client/volumepath/v1alpha1/clientset/versioned"
	internalinterfaces "github.com/upmio/dbscale-kube/pkg/client/volumepath/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/upmio/dbscale-kube/pkg/client/volumepath/v1alpha1/listers/volumepath/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VolumePathInformer provides access to a shared informer and lister for
// VolumePaths.
type VolumePathInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VolumePathLister
}

type volumePathInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVolumePathInformer constructs a new informer for VolumePath type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumePathInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumePathInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVolumePathInformer constructs a new informer for VolumePath type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumePathInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LvmV1alpha1().VolumePaths().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LvmV1alpha1().VolumePaths().Watch(context.TODO(), options)
			},
		},
		&volumepathv1alpha1.VolumePath{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumePathInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumePathInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumePathInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&volumepathv1alpha1.VolumePath{}, f.defaultInformer)
}

func (f *volumePathInformer) Lister() v1alpha1.VolumePathLister {
	return v1alpha1.NewVolumePathLister(f.Informer().GetIndexer())
}
