/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	hostv1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/host/v1alpha1"
	versioned "github.com/upmio/dbscale-kube/pkg/client/host/v1alpha1/clientset/versioned"
	internalinterfaces "github.com/upmio/dbscale-kube/pkg/client/host/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/upmio/dbscale-kube/pkg/client/host/v1alpha1/listers/host/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HostInformer provides access to a shared informer and lister for
// Hosts.
type HostInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HostLister
}

type hostInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHostInformer constructs a new informer for Host type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHostInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHostInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHostInformer constructs a new informer for Host type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHostInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HostV1alpha1().Hosts().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HostV1alpha1().Hosts().Watch(context.TODO(), options)
			},
		},
		&hostv1alpha1.Host{},
		resyncPeriod,
		indexers,
	)
}

func (f *hostInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHostInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hostInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hostv1alpha1.Host{}, f.defaultInformer)
}

func (f *hostInformer) Lister() v1alpha1.HostLister {
	return v1alpha1.NewHostLister(f.Informer().GetIndexer())
}
