/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/san/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLungroups implements LungroupInterface
type FakeLungroups struct {
	Fake *FakeSanV1alpha1
}

var lungroupsResource = schema.GroupVersionResource{Group: "san.upm.io", Version: "v1alpha1", Resource: "lungroups"}

var lungroupsKind = schema.GroupVersionKind{Group: "san.upm.io", Version: "v1alpha1", Kind: "Lungroup"}

// Get takes name of the lungroup, and returns the corresponding lungroup object, and an error if there is any.
func (c *FakeLungroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Lungroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(lungroupsResource, name), &v1alpha1.Lungroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Lungroup), err
}

// List takes label and field selectors, and returns the list of Lungroups that match those selectors.
func (c *FakeLungroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LungroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(lungroupsResource, lungroupsKind, opts), &v1alpha1.LungroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LungroupList{ListMeta: obj.(*v1alpha1.LungroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.LungroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lungroups.
func (c *FakeLungroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(lungroupsResource, opts))
}

// Create takes the representation of a lungroup and creates it.  Returns the server's representation of the lungroup, and an error, if there is any.
func (c *FakeLungroups) Create(ctx context.Context, lungroup *v1alpha1.Lungroup, opts v1.CreateOptions) (result *v1alpha1.Lungroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(lungroupsResource, lungroup), &v1alpha1.Lungroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Lungroup), err
}

// Update takes the representation of a lungroup and updates it. Returns the server's representation of the lungroup, and an error, if there is any.
func (c *FakeLungroups) Update(ctx context.Context, lungroup *v1alpha1.Lungroup, opts v1.UpdateOptions) (result *v1alpha1.Lungroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(lungroupsResource, lungroup), &v1alpha1.Lungroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Lungroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLungroups) UpdateStatus(ctx context.Context, lungroup *v1alpha1.Lungroup, opts v1.UpdateOptions) (*v1alpha1.Lungroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(lungroupsResource, "status", lungroup), &v1alpha1.Lungroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Lungroup), err
}

// Delete takes name of the lungroup and deletes it. Returns an error if one occurs.
func (c *FakeLungroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(lungroupsResource, name), &v1alpha1.Lungroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLungroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(lungroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LungroupList{})
	return err
}

// Patch applies the patch and returns the patched lungroup.
func (c *FakeLungroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Lungroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(lungroupsResource, name, pt, data, subresources...), &v1alpha1.Lungroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Lungroup), err
}
