govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/selection

govendor update k8s.io/kubernetes/vendor/k8s.io/utils/integer
govendor update k8s.io/kubernetes/vendor/github.com/hashicorp/golang-lru/simplelru
govendor update k8s.io/kubernetes/vendor/github.com/google/go-cmp/cmp/internal/diff
govendor update k8s.io/kubernetes/vendor/github.com/google/go-cmp/cmp/internal/flags
govendor update k8s.io/kubernetes/vendor/k8s.io/utils/buffer
govendor update k8s.io/kubernetes/vendor/github.com/golang/groupcache/lru

govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/exec
govendor update k8s.io/kubernetes/pkg/master/ports
govendor update k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/user
govendor update k8s.io/kubernetes/vendor/golang.org/x/xerrors/internal


govendor update k8s.io/kubernetes/vendor/golang.org/x/text/transform

govendor update k8s.io/kubernetes/pkg/capabilities

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/clock

govendor update k8s.io/kubernetes/vendor/golang.org/x/sys/unix
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/rand

govendor update k8s.io/kubernetes/vendor/github.com/gogo/protobuf/sortkeys
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets

govendor update k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/terminal

govendor update k8s.io/kubernetes/vendor/github.com/google/gofuzz
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/fields
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/errors
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field

govendor update k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto
govendor update k8s.io/kubernetes/vendor/gopkg.in/inf.v0

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/resource

govendor update k8s.io/kubernetes/vendor/k8s.io/klog
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/queryparams
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/json
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/naming
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/types

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/intstr

govendor update k8s.io/kubernetes/vendor/golang.org/x/text/unicode/bidi
govendor update k8s.io/kubernetes/vendor/golang.org/x/text/secure/bidirule

govendor update k8s.io/kubernetes/vendor/golang.org/x/text/unicode/norm
govendor update k8s.io/kubernetes/vendor/golang.org/x/net/http2/hpack

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/labels

govendor update k8s.io/kubernetes/vendor/golang.org/x/net/idna

govendor update k8s.io/kubernetes/vendor/golang.org/x/net/http/httpguts
govendor update k8s.io/kubernetes/vendor/github.com/modern-go/concurrent
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/recognizer
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/framer
govendor update k8s.io/kubernetes/vendor/github.com/modern-go/reflect2
govendor update k8s.io/kubernetes/vendor/gopkg.in/yaml.v2

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/version
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version
govendor update k8s.io/kubernetes/vendor/github.com/davecgh/go-spew/spew
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/metrics
govendor update k8s.io/kubernetes/vendor/golang.org/x/net/context
govendor update k8s.io/kubernetes/vendor/golang.org/x/time/rate
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/flowcontrol
govendor update k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto
govendor update k8s.io/kubernetes/vendor/github.com/json-iterator/go
govendor update k8s.io/kubernetes/vendor/sigs.k8s.io/yaml
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml
govendor update k8s.io/kubernetes/vendor/github.com/hashicorp/golang-lru
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/cache
govendor update k8s.io/kubernetes/vendor/github.com/google/go-cmp/cmp/internal/function
govendor update k8s.io/kubernetes/vendor/github.com/google/go-cmp/cmp/internal/value
govendor update k8s.io/kubernetes/vendor/github.com/google/go-cmp/cmp
govendor update k8s.io/kubernetes/vendor/github.com/golang/protobuf/ptypes/any
govendor update k8s.io/kubernetes/vendor/github.com/golang/protobuf/ptypes/duration
govendor update k8s.io/kubernetes/vendor/github.com/golang/protobuf/ptypes/timestamp
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/diff
govendor update k8s.io/kubernetes/vendor/github.com/golang/protobuf/ptypes
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait
govendor update k8s.io/kubernetes/vendor/k8s.io/utils/trace
govendor update k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/extensions
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/mergepatch
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/json
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue

govendor update k8s.io/kubernetes/vendor/github.com/imdario/mergo

govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api/v1
govendor update k8s.io/kubernetes/vendor/github.com/spf13/pflag
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/homedir

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/netutil
govendor update k8s.io/kubernetes/vendor/github.com/opencontainers/go-digest
govendor update k8s.io/kubernetes/vendor/github.com/docker/distribution/digestset
govendor update k8s.io/kubernetes/vendor/github.com/docker/distribution/reference
govendor update k8s.io/kubernetes/pkg/util/parsers
govendor update k8s.io/kubernetes/vendor/k8s.io/utils/pointer
govendor update k8s.io/kubernetes/vendor/k8s.io/utils/net
govendor update k8s.io/kubernetes/vendor/k8s.io/utils/path
govendor update k8s.io/kubernetes/vendor/golang.org/x/crypto/ed25519/internal/edwards25519
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json
govendor update k8s.io/kubernetes/vendor/gopkg.in/square/go-jose.v2/cipher
govendor update k8s.io/kubernetes/vendor/gopkg.in/square/go-jose.v2/json
govendor update k8s.io/kubernetes/vendor/golang.org/x/crypto/ed25519
govendor update k8s.io/kubernetes/pkg/util/hash

govendor update k8s.io/kubernetes/vendor/golang.org/x/xerrors
govendor update k8s.io/kubernetes/vendor/github.com/astaxie/beego/config
govendor update k8s.io/kubernetes/vendor/k8s.io/component-base/logs
govendor update k8s.io/kubernetes/vendor/k8s.io/component-base/featuregate
govendor update k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/feature
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/features
govendor update k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/features
govendor update k8s.io/kubernetes/pkg/features

govendor update k8s.io/kubernetes/vendor/github.com/containernetworking/cni/pkg/types
govendor update k8s.io/kubernetes/vendor/github.com/containernetworking/cni/pkg/types/020
govendor update k8s.io/kubernetes/vendor/github.com/containernetworking/cni/pkg/types/current
govendor update k8s.io/kubernetes/vendor/github.com/google/uuid
govendor update k8s.io/kubernetes/vendor/github.com/containernetworking/cni/pkg/version
govendor update k8s.io/kubernetes/vendor/github.com/containernetworking/cni/pkg/skel

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/uuid

govendor update k8s.io/kubernetes/vendor/github.com/evanphx/json-patch
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/keyutil
govendor update k8s.io/kubernetes/vendor/gopkg.in/square/go-jose.v2

govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/cert
govendor update k8s.io/kubernetes/vendor/gopkg.in/square/go-jose.v2/jwt

govendor update k8s.io/kubernetes/vendor/github.com/gorilla/mux
govendor update k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/compiler
govendor update k8s.io/kubernetes/vendor/golang.org/x/net/http2
govendor update k8s.io/kubernetes/vendor/golang.org/x/oauth2/internal
govendor update k8s.io/kubernetes/vendor/golang.org/x/oauth2
govendor update k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/OpenAPIv2
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream
govendor update k8s.io/kubernetes/vendor/github.com/docker/spdystream/spdy

govendor update k8s.io/kubernetes/vendor/github.com/docker/spdystream
govendor update k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/authenticator

govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/transport
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/util/proto
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/apis/clientauthentication
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/rest/watch
govendor update k8s.io/kubernetes/vendor/k8s.io/api/admissionregistration/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/core/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/auditregistration/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/exec
govendor update k8s.io/kubernetes/vendor/k8s.io/api/authentication/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/rest
govendor update k8s.io/kubernetes/vendor/k8s.io/api/authentication/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/authorization/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/authorization/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/certificates/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/coordination/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/coordination/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/node/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/node/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/rbac/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/rbac/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/rbac/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/meta
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/util/retry
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/strategicpatch
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/auth
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api/latest
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/pager
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/remotecommand
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy
govendor update k8s.io/kubernetes/pkg/api/legacyscheme
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/equality
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation
govendor update k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/validation
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/transport/spdy
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic
govendor update k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/serviceaccount
govendor update k8s.io/kubernetes/pkg/apis/core
govendor update k8s.io/kubernetes/pkg/fieldpath
govendor update k8s.io/kubernetes/pkg/apis/core/pods
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/admissionregistration/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/auditregistration/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/certificates/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/coordination/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/coordination/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/node/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/node/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/rbac/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/rbac/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/rbac/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamiclister
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/watch
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/component-base/config
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/testing
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/fake
govendor update k8s.io/kubernetes/pkg/api/service
govendor update k8s.io/kubernetes/pkg/apis/autoscaling
govendor update k8s.io/kubernetes/pkg/apis/core/helper
govendor update k8s.io/kubernetes/pkg/apis/scheduling
govendor update k8s.io/kubernetes/pkg/apis/apps
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/autoscaling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/apps/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/apps/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/apps/v1beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/api/autoscaling/v2beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/autoscaling/v2beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/api/batch/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/events/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/extensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/batch/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/batch/v2alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/networking/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/networking/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/policy/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/scheduling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/scheduling/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/scheduling/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/settings/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/storage/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/storage/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/api/storage/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/reference
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/apps/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/apps/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/apps/v1beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/autoscaling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/autoscaling/v2beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/autoscaling/v2beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/batch/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/batch/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/batch/v2alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/core/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/events/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/networking/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/networking/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/policy/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/scheduling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/scheduling/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/scheduling/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/settings/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/storage/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/storage/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/storage/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/util
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand
govendor update k8s.io/kubernetes/pkg/api/v1/pod
govendor update k8s.io/kubernetes/pkg/apis/core/v1
govendor update k8s.io/kubernetes/pkg/apis/core/v1/helper
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/scheme
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/listers/extensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/discovery
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/apps/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/authentication/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/authentication/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/authorization/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/authorization/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/autoscaling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/batch/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/batch/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/batch/v2alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/certificates/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/coordination/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/coordination/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/events/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/networking/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/networking/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/node/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/node/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/policy/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/rbac/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/rbac/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/scheduling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/scheduling/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/settings/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/storage/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/storage/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/storage/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes
govendor update k8s.io/kubernetes/pkg/apis/core/install
govendor update k8s.io/kubernetes/pkg/kubelet/types
govendor update k8s.io/kubernetes/pkg/security/apparmor
govendor update k8s.io/kubernetes/pkg/serviceaccount
govendor update k8s.io/kubernetes/pkg/apis/core/validation
govendor update k8s.io/kubernetes/pkg/util/taints
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/internalinterfaces
govendor update k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/admissionregistration/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/apps/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/admissionregistration
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/apps/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/apps/v1beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/auditregistration/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/auditregistration
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/autoscaling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/apps
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/autoscaling/v2beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/autoscaling/v2beta2
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/batch/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/batch/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/autoscaling
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/batch/v2alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/certificates/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/coordination/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/coordination/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/batch
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/certificates
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/core/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/coordination
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/events/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/extensions/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/networking/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/events
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/networking/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/node/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/extensions
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/networking
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/core
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/node/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/policy/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/rbac/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/node
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/rbac/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/policy
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/rbac/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/scheduling/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/scheduling/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/scheduling/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/rbac
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/settings/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/storage/v1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/scheduling
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/storage/v1alpha1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/settings
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/storage/v1beta1
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/resourcelock
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers/storage
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/informers
govendor update k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamicinformer
govendor update k8s.io/kubernetes/pkg/controller
