/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/networking/v1alpha1"
	scheme "github.com/upmio/dbscale-kube/pkg/client/networking/v1alpha1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkClaimsGetter has a method to return a NetworkClaimInterface.
// A group's client should implement this interface.
type NetworkClaimsGetter interface {
	NetworkClaims() NetworkClaimInterface
}

// NetworkClaimInterface has methods to work with NetworkClaim resources.
type NetworkClaimInterface interface {
	Create(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.CreateOptions) (*v1alpha1.NetworkClaim, error)
	Update(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (*v1alpha1.NetworkClaim, error)
	UpdateStatus(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (*v1alpha1.NetworkClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkClaim, err error)
	NetworkClaimExpansion
}

// networkClaims implements NetworkClaimInterface
type networkClaims struct {
	client rest.Interface
}

// newNetworkClaims returns a NetworkClaims
func newNetworkClaims(c *NetworkingV1alpha1Client) *networkClaims {
	return &networkClaims{
		client: c.RESTClient(),
	}
}

// Get takes name of the networkClaim, and returns the corresponding networkClaim object, and an error if there is any.
func (c *networkClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkClaim, err error) {
	result = &v1alpha1.NetworkClaim{}
	err = c.client.Get().
		Resource("networkclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkClaims that match those selectors.
func (c *networkClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkClaimList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkClaimList{}
	err = c.client.Get().
		Resource("networkclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkClaims.
func (c *networkClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("networkclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkClaim and creates it.  Returns the server's representation of the networkClaim, and an error, if there is any.
func (c *networkClaims) Create(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.CreateOptions) (result *v1alpha1.NetworkClaim, err error) {
	result = &v1alpha1.NetworkClaim{}
	err = c.client.Post().
		Resource("networkclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkClaim).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkClaim and updates it. Returns the server's representation of the networkClaim, and an error, if there is any.
func (c *networkClaims) Update(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (result *v1alpha1.NetworkClaim, err error) {
	result = &v1alpha1.NetworkClaim{}
	err = c.client.Put().
		Resource("networkclaims").
		Name(networkClaim.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkClaim).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *networkClaims) UpdateStatus(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (result *v1alpha1.NetworkClaim, err error) {
	result = &v1alpha1.NetworkClaim{}
	err = c.client.Put().
		Resource("networkclaims").
		Name(networkClaim.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkClaim).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkClaim and deletes it. Returns an error if one occurs.
func (c *networkClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("networkclaims").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("networkclaims").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkClaim.
func (c *networkClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkClaim, err error) {
	result = &v1alpha1.NetworkClaim{}
	err = c.client.Patch(pt).
		Resource("networkclaims").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
