/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	sanv1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/san/v1alpha1"
	versioned "github.com/upmio/dbscale-kube/pkg/client/san/v1alpha1/clientset/versioned"
	internalinterfaces "github.com/upmio/dbscale-kube/pkg/client/san/v1alpha1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/upmio/dbscale-kube/pkg/client/san/v1alpha1/listers/san/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SanSystemInformer provides access to a shared informer and lister for
// SanSystems.
type SanSystemInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SanSystemLister
}

type sanSystemInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSanSystemInformer constructs a new informer for SanSystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSanSystemInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSanSystemInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSanSystemInformer constructs a new informer for SanSystem type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSanSystemInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SanV1alpha1().SanSystems().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SanV1alpha1().SanSystems().Watch(context.TODO(), options)
			},
		},
		&sanv1alpha1.SanSystem{},
		resyncPeriod,
		indexers,
	)
}

func (f *sanSystemInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSanSystemInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sanSystemInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sanv1alpha1.SanSystem{}, f.defaultInformer)
}

func (f *sanSystemInformer) Lister() v1alpha1.SanSystemLister {
	return v1alpha1.NewSanSystemLister(f.Informer().GetIndexer())
}
