/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/volumepath/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VolumePathLister helps list VolumePaths.
type VolumePathLister interface {
	// List lists all VolumePaths in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.VolumePath, err error)
	// Get retrieves the VolumePath from the index for a given name.
	Get(name string) (*v1alpha1.VolumePath, error)
	VolumePathListerExpansion
}

// volumePathLister implements the VolumePathLister interface.
type volumePathLister struct {
	indexer cache.Indexer
}

// NewVolumePathLister returns a new VolumePathLister.
func NewVolumePathLister(indexer cache.Indexer) VolumePathLister {
	return &volumePathLister{indexer: indexer}
}

// List lists all VolumePaths in the indexer.
func (s *volumePathLister) List(selector labels.Selector) (ret []*v1alpha1.VolumePath, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VolumePath))
	})
	return ret, err
}

// Get retrieves the VolumePath from the index for a given name.
func (s *volumePathLister) Get(name string) (*v1alpha1.VolumePath, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("volumepath"), name)
	}
	return obj.(*v1alpha1.VolumePath), nil
}
