/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkClaims implements NetworkClaimInterface
type FakeNetworkClaims struct {
	Fake *FakeNetworkingV1alpha1
}

var networkclaimsResource = schema.GroupVersionResource{Group: "networking.upm.io", Version: "v1alpha1", Resource: "networkclaims"}

var networkclaimsKind = schema.GroupVersionKind{Group: "networking.upm.io", Version: "v1alpha1", Kind: "NetworkClaim"}

// Get takes name of the networkClaim, and returns the corresponding networkClaim object, and an error if there is any.
func (c *FakeNetworkClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkclaimsResource, name), &v1alpha1.NetworkClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkClaim), err
}

// List takes label and field selectors, and returns the list of NetworkClaims that match those selectors.
func (c *FakeNetworkClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkclaimsResource, networkclaimsKind, opts), &v1alpha1.NetworkClaimList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkClaimList{ListMeta: obj.(*v1alpha1.NetworkClaimList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkClaims.
func (c *FakeNetworkClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkclaimsResource, opts))
}

// Create takes the representation of a networkClaim and creates it.  Returns the server's representation of the networkClaim, and an error, if there is any.
func (c *FakeNetworkClaims) Create(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.CreateOptions) (result *v1alpha1.NetworkClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkclaimsResource, networkClaim), &v1alpha1.NetworkClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkClaim), err
}

// Update takes the representation of a networkClaim and updates it. Returns the server's representation of the networkClaim, and an error, if there is any.
func (c *FakeNetworkClaims) Update(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (result *v1alpha1.NetworkClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkclaimsResource, networkClaim), &v1alpha1.NetworkClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkClaims) UpdateStatus(ctx context.Context, networkClaim *v1alpha1.NetworkClaim, opts v1.UpdateOptions) (*v1alpha1.NetworkClaim, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networkclaimsResource, "status", networkClaim), &v1alpha1.NetworkClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkClaim), err
}

// Delete takes name of the networkClaim and deletes it. Returns an error if one occurs.
func (c *FakeNetworkClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networkclaimsResource, name), &v1alpha1.NetworkClaim{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkclaimsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkClaimList{})
	return err
}

// Patch applies the patch and returns the patched networkClaim.
func (c *FakeNetworkClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkclaimsResource, name, pt, data, subresources...), &v1alpha1.NetworkClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkClaim), err
}
