/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/upmio/dbscale-kube/pkg/apis/san/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SanSystemLister helps list SanSystems.
type SanSystemLister interface {
	// List lists all SanSystems in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.SanSystem, err error)
	// Get retrieves the SanSystem from the index for a given name.
	Get(name string) (*v1alpha1.SanSystem, error)
	SanSystemListerExpansion
}

// sanSystemLister implements the SanSystemLister interface.
type sanSystemLister struct {
	indexer cache.Indexer
}

// NewSanSystemLister returns a new SanSystemLister.
func NewSanSystemLister(indexer cache.Indexer) SanSystemLister {
	return &sanSystemLister{indexer: indexer}
}

// List lists all SanSystems in the indexer.
func (s *sanSystemLister) List(selector labels.Selector) (ret []*v1alpha1.SanSystem, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SanSystem))
	})
	return ret, err
}

// Get retrieves the SanSystem from the index for a given name.
func (s *sanSystemLister) Get(name string) (*v1alpha1.SanSystem, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("sansystem"), name)
	}
	return obj.(*v1alpha1.SanSystem), nil
}
